version: '3.8'

services:
  cassandra-node1:
    image: cassandra:4.1
    container_name: cassandra-node1
    hostname: cassandra-node1
    networks:
      - cassandra-network
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2
      - CASSANDRA_NUM_TOKENS=256
    volumes:
      - cassandra_data1:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe cluster' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 90s

  cassandra-node2:
    image: cassandra:4.1
    container_name: cassandra-node2
    hostname: cassandra-node2
    networks:
      - cassandra-network
    ports:
      - "9043:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2
      - CASSANDRA_NUM_TOKENS=256
    volumes:
      - cassandra_data2:/var/lib/cassandra
    depends_on:
      cassandra-node1:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe cluster' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 90s

  cassandra-node3:
    image: cassandra:4.1
    container_name: cassandra-node3
    hostname: cassandra-node3
    networks:
      - cassandra-network
    ports:
      - "9044:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2
      - CASSANDRA_NUM_TOKENS=256
    volumes:
      - cassandra_data3:/var/lib/cassandra
    depends_on:
      cassandra-node2:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe cluster' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 90s

  # Cassandra Web UI 제거 - 대신 cqlsh 또는 다른 GUI 도구 사용 권장
  # cassandra-web 이미지들이 제대로 작동하지 않아 제거합니다.
  # 대안:
  # 1. docker exec -it cassandra-node1 cqlsh (명령줄)
  # 2. TablePlus, DBeaver 등의 데스크톱 GUI 도구
  # 3. DataStax Studio (무료, 다운로드 필요)

networks:
  cassandra-network:
    driver: bridge

volumes:
  cassandra_data1:
  cassandra_data2:
  cassandra_data3: